ExportOptions.plist & Provisioning Profiles Subfolder functionality A…
lionstudios/auto-builder pull request #21
Opened 2023-10-02 17:47 UTC by BhaumikLion

…dded

2023-10-03 20:41 UTC, jquentin-lion requested changes

2023-10-03 20:41 UTC, jquentin-lion commented on Packages/AutomatedBuilding/Editor/Builder/IOSBuilder.cs
> +                    // Debug.Log("Settings is not null anymore.." + _iosBuildSettings);
No dead code. Uncomment or remove.

2023-10-03 20:41 UTC, jquentin-lion commented on Packages/AutomatedBuilding/Editor/Builder/IOSBuilder.cs
> +            //Debug.Log("Path for Provisioning Profile: " + PROVISIONING_PROFILE_PATH + ProvisionalProfileName + ".mobileprovision");
No dead code. Uncomment or remove.

2023-10-04 11:09 UTC, BhaumikLion commented on Packages/AutomatedBuilding/Editor/Builder/IOSBuilder.cs
> +                    // Debug.Log("Settings is not null anymore.." + _iosBuildSettings);
removed

2023-10-04 11:09 UTC, BhaumikLion commented on Packages/AutomatedBuilding/Editor/Builder/IOSBuilder.cs
> +            //Debug.Log("Path for Provisioning Profile: " + PROVISIONING_PROFILE_PATH + ProvisionalProfileName + ".mobileprovision");
removed

2023-10-11 16:14 UTC, jquentin-lion approved these changes

2023-10-11 16:15 UTC, merged